baseURL = 'https://tpellet.github.io/pellet-personal-website/'
locale = 'en-US'
title = 'Thomas Pellet'
theme = 'minimal-portfolio'

[params]
  author = "Thomas Pellet"
  description = "Data scientist and economist. Software, research, and a PhD in Economics from Northwestern University."
  github = "https://github.com/tpellet"
  linkedin = "https://linkedin.com/in/thomaspellet"
  email = "pellet.thomas@gmail.com"
  resume = "resume/curriculum_vitae_Thomas_Pellet.pdf"

[menu]
  [[menu.main]]
    name = "Software"
    pageRef = "/projects"
    weight = 1
  [[menu.main]]
    name = "Research"
    pageRef = "/publications"
    weight = 2
  [[menu.main]]
    name = "Résumé"
    pageRef = "/resume"
    weight = 3

[outputs]
  home = ["HTML"]
  section = ["HTML"]

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
